name: dart_backend
description: Dart backend server for Stark Tech Flutter app

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  mongo_dart: ^0.9.3
  dotenv: ^4.2.0
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
