[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "dart run lib/server.dart"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = { default = "8080" }
HOST = { default = "0.0.0.0" }
