name: Deploy Stark Tech App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
    
    - name: Install dependencies
      run: |
        cd dart_backend
        dart pub get
    
    - name: Run tests (if any)
      run: |
        cd dart_backend
        dart test || echo "No tests found"
    
    - name: Deploy to Railway
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        echo "Deploy to Railway using their CLI or API"
        # Add Railway deployment commands here

  deploy-flutter-web:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
    
    - name: Install dependencies
      run: |
        cd starktech_flutter
        flutter pub get
    
    - name: Build web
      run: |
        cd starktech_flutter
        flutter build web --release
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./starktech_flutter/build/web
        cname: your-domain.com  # Optional: replace with your custom domain
